### ISSUE TITLE
ERROR [2/2] RUN apt-get update &&     apt-get -y install git &&

### ISSUE THREAD

**Issue by dev-naddari** [Rikj000/MoniGoMani#4]
Hello 
I had an error during installation, any hint please:

docker-compose pull
Pulling freqtrade ... done 

docker-compose up --build
Building freqtrade
failed to get console mode for stdout: The handle is invalid.
[+] Building 1.0s (4/5)
 => [internal] load build definition from Dockerfile.technical             0.0s
[+] Building 1.1s (5/5) FINISHED
 => [internal] load build definition from Dockerfile.technical             0.0s
 => => transferring dockerfile: 42B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/freqtradeorg/freqtrade:develop  0.0s
 => [1/2] FROM docker.io/freqtradeorg/freqtrade:develop                    0.1st &&     apt-get clean &&     pip install
 **=> ERROR [2/2] RUN apt-get update &&     apt-get -y install git &&**     a  0.8s
------
 > [2/2] RUN apt-get update &&     apt-get -y install git &&     apt-get clean &&     pip install git+https://github.com/freqtrade/technical:
#5 0.224 Reading package lists...
#5 0.816 E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
#5 0.816 E: Unable to lock directory /var/lib/apt/lists/
------
ERROR: Service 'freqtrade' failed to build

**Comment by Rikj000** [comment]
Correct, I experienced this issue today too, I resolved it by doing the following 2 things:   
-[Download](https://github.com/freqtrade/freqtrade/tree/develop/docker) & the latest official Freqtrade `docker` folder & `Dockerfile.`'s that are within & replace the ones in `MoniGoMani/docker/` with these.   
-Update your `docker-compose.yml` as following:
```yml
---
version: '3'
services:
  freqtrade:
    # image: freqtradeorg/freqtrade:stable
    image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #  context: .
    #  dockerfile: "./docker/Dockerfile.technical"
    restart: unless-stopped
    container_name: Freqtrade-MoniGoMani
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3-MoniGoMani_v0.8.1.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/config-private.json
      --strategy MoniGoManiHyperStrategy
```
- Stop & delete your current `Freqtrade-MoniGoMani`container   
- Do `docker-compose pull` & `docker-compose --build --force-recreate`   
   
After that your problem should be resolved, these fixes will be included in **v0.9.0** once it is complete.
